version: "3.8"
services:
  logger_service:
    container_name: logger_service
    image: finx_logger_service_sapi
    build: .
    restart: always
    ports:
      - '9016:8080'
    environment:
      SERVICE_PORT: 8080

