# QA Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:qa-postgres}:${DB_PORT:5432}/${DB_NAME:finx_payload_qa}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:finx_user}
    password: ${DB_PASSWORD:finx_pass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.finx: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: logs/finx-payload-transformer-qa.log
    max-size: 50MB
    max-history: 10

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# QA specific configurations
finx:
  payload-transformer:
    debug-mode: false
    log-transformations: true
    mock-external-apis: false
    validation-strict: true
    qa-test-mode: true