server:
  port: ${SERVICE_PORT:8088}

spring:
  main:
    log-startup-info: true
    banner-mode: console
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: finx-payload-transformer-service
